Repository openjs-foundation/cross-project-council, pull requests merged in 2018-12, with the labels that each got.

#41 EXPECTATIONS stage 1
  proposals/README.md
  proposals/hackygolucky-EXPECTATIONS/EXPECTATIONS.md
  proposals/hackygolucky-EXPECTATIONS/README.md
Labels: bootstrap-agenda, do not merge, stage-1

#54 doc: fix spelling in template
  proposals/TEMPLATE.md
Labels: bootstrap-agenda

#53 doc: update proposal template
  proposals/TEMPLATE.md
Labels: bootstrap-agenda

#55 proposal: town-hall to stage 0
  proposals/README.md
  proposals/stage-0/regular-town-halls/README.md
Labels: bootstrap-agenda

#45 [WIP] PROJECT PROGRESSION
  proposals/README.md
  proposals/jorydotcom-PROJECT_PROGRESSION/PROJECT_PROGRESSION.md
  proposals/jorydotcom-PROJECT_PROGRESSION/README.md
Labels: bootstrap-agenda, stage-1
