Repository openjs-foundation/cross-project-council, pull requests merged in 2019-08, with the labels that each got.

#274 doc: add gov for first term of voting members
  GOVERNANCE.md
Labels: cross-project-council-agenda, governance

#301 doc: remove "tbd pending outcome" from PROJECT_PROGRESSION
  PROJECT_PROGRESSION.md
Labels: documentation

#275 doc: swapping refs to TAC with CPC
  CPC-CHARTER.md
Labels: blocked, governance

#303 doc: add august 6 + 13 meeting notes
  meetings/2019-08-06.md
  meetings/2019-08-13.md
Labels: documentation

#294 doc: rename acceptance criteria to graduation criteria
  PROJECT_PROGRESSION.md
Labels: cross-project-council-agenda, governance, onboarding
