Repository openjs-foundation/cross-project-council, pull requests merged in 2019-06, with the labels that each got.

#187 Added collab summit proposal
  proposals/stage-1/COLLAB_SUMMIT/README.md
Labels: cross-project-council-agenda, stage-1

#182 doc: update readme for CPC
  README.md
  artifacts/BOOTSTRAP_README.md
Labels: cross-project-council-agenda

#201 doc: fix missing header in charter
  CPC-CHARTER.md
Labels: blocked

#205 doc: clarify guidance for landing PRs
  GOVERNANCE.md
Labels: cross-project-council-agenda
