Repository openjs-foundation/cross-project-council, pull requests merged in 2019-09, with the labels that each got.

#297 doc: add governance for adding regular members
  GOVERNANCE.md
Labels: governance

#302 governance: add fast-track
  GOVERNANCE.md
Labels: governance

#308 Add Markdown linter
  .gitignore
  .remarkrc
  .travis.yml
  GOVERNANCE.md
  meetings/2019-01-07.md
  package-lock.json
  package.json
  proposals/stage-2/TRAVEL_FUND/travel-visas.md
Labels: enhancement

#314 minor spelling fixes in the Governance
  GOVERNANCE.md
Labels: fast-track, governance

#304 doc: remove duplicate checklist
  .github/ISSUE_TEMPLATE/project-onboarding-checklist-template.md
  NEW_PROJECT_APPLICATION.md
  PROJECT_PROGRESSION.md
Labels: documentation

#305 charter: s/maintainers/governing body
  CPC-CHARTER.md
Labels: blocked, board approval required, cross-project-council-agenda, governance

#319 doc: expectations for dissent / objections
  MEMBER_EXPECTATIONS.md
Labels: governance

#313 Add project exit criteria
  proposals/stage-0/PROJECT_EXIT_CRITERIA/README.md
Labels: stage-0

#271 Add process for handling reports
  proposals/stage-1/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
  proposals/stage-1/CODE_OF_CONDUCT/HANDLING-REPORTS.md
  proposals/stage-1/CODE_OF_CONDUCT/README.md
Labels: stage-1

#325 doc: add exit criteria proposal to proposal list
  proposals/README.md
Labels: fast-track

#332 doc: add missing meeting notes
  meetings/2019-08-20.md
  meetings/2019-08-27.md
  meetings/2019-09-03.md
  meetings/2019-09-10.md
  meetings/2019-09-17.md
Labels: fast-track
