Repository openjs-foundation/cross-project-council, pull requests merged in 2019-10, with the labels that each got.

#337 doc: adding meeting notes Sep 24 and Oct 1
  meetings/2019-09-24.md
  meetings/2019-10-01.md
Labels: fast-track

#346 Add AMP to Incubating Projects, update PROJECTS.md
  PROJECTS.md
  README.md
Labels: fast-track

#347 Fix https -> http link for nvm
  PROJECTS.md
  README.md
Labels: fast-track

#279 adds a draft charter template
  PROJECT_CHARTER_TEMPLATE.md
Labels: governance

#330 doc: Move COC proposal to stage 2
  proposals/README.md
  proposals/stage-2/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md
  proposals/stage-2/CODE_OF_CONDUCT/HANDLING-REPORTS.md
  proposals/stage-2/CODE_OF_CONDUCT/README.md
Labels: cross-project-council-agenda

#351 doc: adding meeting notes Oct 8 and 15
  meetings/2019-10-08.md
  meetings/2019-10-15.md
Labels: fast-track

#321 doc: update PROJECT_PROGRESSION.md
  NEW_PROJECT_APPLICATION.md
  PROJECT_PROGRESSION.md
Labels: board approval required, governance

#384 [meta] remove stray quote in CoC
  CODE_OF_CONDUCT.md
Labels: fast-track
