Repository openjs-foundation/cross-project-council, pull requests merged in 2020-05, with the labels that each got.

#495 Amendment to the by laws to ensure a sign-off between Voting CPC members
  CPC-CHARTER.md
Labels: board approval required, cross-project-council-agenda

#544 make it clearer there are two proposals
  mentorship/2020/google-season-of-docs/README.md
Labels: fast-track

#508 Specify non-impact voting CPC member election timeframe
  GOVERNANCE.md
Labels: governance

#531 Updating requirements to become a regular member
  .github/PULL_REQUEST_TEMPLATE/regular-member-pull-request.md
  CPC-CHARTER.md
  GOVERNANCE.md
  README.md
Labels: board approval required, cross-project-council-agenda, waiting on board

#541 Adding Code of Conduct WG charter
  WORKING_GROUPS.md
Labels: cross-project-council-agenda

#548 doc: move collaboration network proposal to stage 1
  proposals/README.md
  proposals/stage-1/COLLABORATION_NETWORK/COLLABORATION_NETWORK.md
  proposals/stage-1/COLLABORATION_NETWORK/COLLABORATION_SPACE_PROGRESSION.md
  proposals/stage-1/COLLABORATION_NETWORK/README.md
Labels: cross-project-council-agenda
