Repository openjs-foundation/cross-project-council, pull requests merged in 2020-08, with the labels that each got.

#587 Board seat definitions and process
  CPC-CHARTER.md
  GOVERNANCE.md
Labels: cross-project-council-agenda, governance

#591 Use simple PR rather than 2/3 vote to graduate projects from incubation
  PROJECTS.md
  PROJECT_PROGRESSION.md
Labels: waiting on board

#596 Drop charter mention of Commons.js
  CPC-CHARTER.md
Labels: board approval required, governance

#619 Ads links to CPC members' GitHub profiles
  README.md
Labels: fast-track

#609 Update term dates and lengths for CPC Directors
  GOVERNANCE.md
Labels: governance
