Repository openjs-foundation/cross-project-council, pull requests merged in 2020-01, with the labels that each got.

#413 Add a copy of the Contributor Covenant CoC text
  CODE_OF_CONDUCT.md
Labels: cross-project-council-agenda

#442 doc: adding 2020-01-07 meeting notes
  meetings/2020-01-07.md
Labels: fast-track

#405 adds proposal for charter submission & review per #200
  proposals/stage-1/CHARTER_REVIEW/README.md
  proposals/stage-1/CHARTER_REVIEW/charter_review.md
Labels: cross-project-council-agenda, governance, stage-1

#451 doc: fix a link of Code of Conduct governance document
  CODE_OF_CONDUCT.md
Labels: fast-track

#452 doc: fix links in proposals index
  proposals/README.md
Labels: fast-track

#454 doc: add allocation for 2020
  MEMBER_TRAVEL_FUND.md
Labels: fast-track
