Repository openjs-foundation/cross-project-council, pull requests merged in 2020-10, with the labels that each got.

#659 Add ICLA-only option to IP Policy Guidance
  IP_POLICY_GUIDANCE.md
Labels: cross-project-council-agenda

#595 doc: move collaboration network proposal to stage 3
  COLLABORATION_NETWORK.md
  COLLABORATION_SPACE_PROGRESSION.md
  NEW_COLLABORATION_SPACE_APPLICATION.md
  proposals/stage-3/COLLABORATION_NETWORK/README.md
Labels: blocked, board approval required

#547 doc: Governance changes for Collaboration Network
  CPC-CHARTER.md
  README.md
Labels: board approval required, cross-project-council-agenda

#643 Add examples of successful applications
  PROJECT_PROGRESSION.md
Labels: cross-project-council-agenda
