Repository openjs-foundation/cross-project-council, pull requests merged in 2022-04, with the labels that each got.

#853 Minor update to legal-questions instructions
  README.md
Labels: documentation

#869 Fix broken links
  .github/PULL_REQUEST_TEMPLATE/regular-member-pull-request.md
  .github/workflows/link-checker.yml
  CODE_OF_CONDUCT.md
  CPC-CHARTER.md
  PROJECT_PROGRESSION.md
  conduct/HANDLING_CODE_OF_CONDUCT_REPORTS.md
  governance/GOVERNANCE.md
  governance/WORKING_GROUPS.md
  governance/transfer-repo-into-org.md
  meetings/2019/2019-04-01.md
  meetings/2020/2020-09-29.md
  meetings/2020/2020-12-15.md
  meetings/2021/2021-05-25.md
  meetings/2021/2021-07-20.md
  meetings/2021/2021-08-03.md
  meetings/2022/2022-03-15.md
  meetings/2022/2022-03-29.md
  proposals/approved/SECURITY_REPORTING/README.md
  proposals/incubating/CHARTER_REVIEW/charter_review.md
Labels: fast-track

#865 Add travel fund request for OpenJS World 2022
  TRAVEL_FUND/2022.md
  TRAVEL_FUND/Achived_Travel_Fund_Records/2021.md
  project-resources/MEMBER_TRAVEL_FUND.md
Labels: cross-project-council-agenda

#868 Travel Fund Request @waleedashraf - OpenJS World - Austin
  TRAVEL_FUND/2022.md
Labels: cross-project-council-agenda, fast-track

#871 Travel Fund Request @dylans - OpenJS World - Austin
  TRAVEL_FUND/2022.md
Labels: cross-project-council-agenda, fast-track

#873 Travel fund request: Eemeli Aro, OpenJS World 2022
  TRAVEL_FUND/2022.md
Labels: fast-track

#876 doc: fix broken URL anchor, grammar
  governance/IP_POLICY_GUIDANCE.md
Labels: fast-track
