Repository openjs-foundation/cross-project-council, pull requests merged in 2025-01, with the labels that each got.

#1404 graduate express to impact stage in readme
  README.md
Labels: fast-track

#1411 Add new CPC members
  README.md
Labels: cross-project-council-agenda, fast-track

#1410 Update requesting_LFIT_support.md
  project-resources/requesting_LFIT_support.md
Labels: cross-project-council-agenda
